### ISSUE TITLE
Should we make it possible for two cells to have the same positon?

### ISSUE THREAD

**Issue by slemonide** [slemonide/sasuga#39]
It could be useful for things like cursor indicator, liquids, small items, etc.

**Comment by Raybotu** [comment]
I say it should be.

The cursor implementation I had in mind is a hollow, transparent block outline that either goes over an existing block or where a block could be placed, depending on whether the mode is set to build or destroy.
In this case, it might be useful to specify that different cells of the same cell type cannot be in the same position, but that they can be in the same position as a cell of another type?

**Comment by slemonide** [comment]
We don't really have to store Cursor in the world.

**Comment by slemonide** [comment]
I mean, we have to render it, but we don't have to store it in the CellsMap.
